### ISSUE TITLE
Relics: Add certain relics to Wandering Trader

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#102]
### Describe your suggestion

To make the Wandering Trader more useful I'd suggest adding a selection of Relics to his pool of available trades. I actually went and experimented with all the relics in Creative and have the following suggestions:

All relic boots can be added as trades, none of them are game breaking or overtuned.
For gloves, only the Mittens should be added
The Shadow Glaive, Magic Mirror, Hunter Belt and Jellyfish Necklace would all be good trades as well

### Why would you like this added/changed?

Gives more variety to the Trader and makes it less tedious trying to find specific relics since they take an eternity to level. I've attached a text doc with my notes on each one if you are interested,
[Trader Relics.txt](https://github.com/user-attachments/files/16817761/Trader.Relics.txt)

**Comment by MuteTiefling** [comment]
Thanks for the suggestion!
