### ISSUE TITLE
PneumaticCraft Acid Etcher Won't Accept Acid in Current Version of the Mod

### ISSUE THREAD

**Issue by Emeny-mne** [EnigmaticaModpacks/Enigmatica10#103]
### Modpack Version

1.9.0

### Describe your issue.

There seems to be no way to place acid into an acid etcher in the PneumaticCraft mod, locking most of the mod's progression. 

After digging through the PneumaticCraft release notes this seems to have been fixed in v8.0.3 of the mod. I'm unable to do any testing with that version because it also updates the mod to use Minecraft version 1.21.1.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Emeny

**Comment by MuteTiefling** [comment]
Thanks for the report. Next version will update to 1.21.1 so this'll be fine then
