### ISSUE TITLE
add deeper darker mod to e10

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#111]
### URL

https://www.curseforge.com/minecraft/mc-mods/deeperdarker

### Why would you like the mod added?

it's an interesting mod
adds some new awesome deco blocks and a new dimension you get to when you light the portal in the ancient city
has new mobs and is sculk based.
moto is intrigued so I got that going for me

**Comment by MuteTiefling** [comment]
Certainly sounds interesting!

**Comment by NielsPilgaard** [comment]
Looks cool, sure!
