### ISSUE TITLE
Opening LaserIO Data Filter crashes player to server screen

### ISSUE THREAD

**Issue by mmerfort** [EnigmaticaModpacks/Enigmatica10#129]
### Modpack Version

1.10.1

### Describe your issue.

When opening (right-clicking into the air) the LaserIO Data Filter, the game crashes to the server selection and shows this error:
![image](https://github.com/user-attachments/assets/507d039c-41f3-469b-acf1-c1e843402e1a)

### Crash Report

https://gist.github.com/mmerfort/60ee76f0d479cf8186feaf988033c517

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, this has been fixed in LaserIO 👍 
https://github.com/Direwolf20-MC/LaserIO/issues/298
