### ISSUE TITLE
Market doesn't drop as an item

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#13]
### Modpack Version

1.2.0

### Describe your issue.

The tooltip shows that you can use an axe to break a Market but if you do, you don't get the Market back.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by MuteTiefling** [comment]
Thanks for the report, will get that relayed shortly.
