### ISSUE TITLE
Alloy Smelter doesn't work for furnace recipes

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica10#134]
### Modpack Version

indev

### Describe your issue.

For tracking purposes

https://github.com/Team-EnderIO/EnderIO/issues/823

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Testing our webhook
