### ISSUE TITLE
upgrading past copper items 

### ISSUE THREAD

**Issue by CrpytTonic** [EnigmaticaModpacks/Enigmatica10#135]
### Modpack Version

Enigmatica 10 1.10.1

### Describe your issue.

every time i make anything with copper like chests and backpacks i can not upgrade them to iron i've gottten it to work once ,and that was it i don't know if it's an issue with placing it down first then upgrading it ,or if it just right out bugged atm i've also tried making fresh ones and still nothing. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Crpyt#4976

**Comment by MuteTiefling** [comment]
Thanks for the report.

I'm afraid I'm having trouble replicating the issue in dev.

 Could you provide more information on the exact items you're crafting and how you're attempting to upgrade them? Screenshots would be extremely helpful.

**Comment by MuteTiefling** [comment]
I'll close this for now. Please feel free to re-open if you're able to reproduce in 1.11+ and can supply the requested information.
