### ISSUE TITLE
Utilitarian

### ISSUE THREAD

**Issue by mmerfort** [EnigmaticaModpacks/Enigmatica10#137]
### URL

https://www.curseforge.com/minecraft/mc-mods/utilitarian

### Why would you like the mod added?

The most interesting features of this mod:
* Angel Block
* No Soliciting (Makes the annoying traders spawn away from your base)
* Fluid hopper (Cheap early alternative to pipes)

It also allows disabling blocks we might not want, like Snad, Drit or Grrass.

If we decide to include it, we could also replace the Ding mod with it.

**Comment by MuteTiefling** [comment]
Seems interesting. Have found one small issue so far.

I think snad/drit/grrass should be disabled for sure. Snad feels like a free version of acceleration chambers and the other two are just really awkward mob spikes.

The rest is good though

**Comment by NielsPilgaard** [comment]
> Seems interesting. Have found[ one small issue](https://github.com/JDKDigital/utilitarian/issues/6) so far.
> 
> I think snad/drit/grrass should be disabled for sure. Snad feels like a free version of acceleration chambers and the other two are just really awkward mob spikes.
> 
> The rest is good though

I agree 👍

**Comment by NielsPilgaard** [comment]
There is no config to remove snad/drit/grrass, so we'll just have to remove the recipes 😅
