### ISSUE TITLE
Occultism: Can't summon foliot crusher

### ISSUE THREAD

**Issue by Seegras** [EnigmaticaModpacks/Enigmatica10#14]
### Modpack Version

1.2.0

### Describe your issue.

summoning foliot crusher in aviar's circle refuses to start, says "Unknown Ritual". Which shouldn't really be the case unless the ingredients (raw iron, copper, gold, silver) have changed (and you can't look them up neither in the book nor in JEI). 

ATM10 has the same problem, so this might be upstreams. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Seegras** [comment]
You can fix it by updating to occultism 1.133.3 (newer than that might also need a news neoforge version).

**Comment by MuteTiefling** [comment]
Thanks for the report. This is duplicated by https://github.com/EnigmaticaModpacks/Enigmatica10/issues/9
