### ISSUE TITLE
Unable to progress in Mekanism quest line.

### ISSUE THREAD

**Issue by capngeo** [EnigmaticaModpacks/Enigmatica10#146]
### Modpack Version

1.10.1

### Describe your issue.

1 of the 4 items requested from the "Metallurgic Infuser" quest is steel dust from Mekanism, but the process to make steel dust through Mekanism yields steel dust from the mod Modern Industrialization.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report. This is already fixed in Dev. 

https://github.com/EnigmaticaModpacks/Enigmatica10/pull/116
