### ISSUE TITLE
Missing item drop from quests

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#151]
### Modpack Version

10.1.0.1

### Describe your issue.

Getting missing item drops from FTB quest line for Occultism. Item says occultism:candle_white  
![2024-10-05_16 58 48](https://github.com/user-attachments/assets/97dd336e-b55e-41ac-9f6c-99aefe932cbe)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by MuteTiefling** [comment]
Thanks for the report. Looks like this one was fixed here https://github.com/EnigmaticaModpacks/Enigmatica10/commit/844891f87f584768a26474d30c4bac7bd9a688bb

But please let us know if you run into any others :D
