### ISSUE TITLE
Connected Glass

### ISSUE THREAD

**Issue by purrloftruth** [EnigmaticaModpacks/Enigmatica10#152]
### URL

https://www.curseforge.com/minecraft/mc-mods/connected-glass

### Why would you like the mod added?

Previously present in E9.

From the mod's description page:

> Connected Glass adds new types of glass with connecting textures! This includes regular, clear, tinted, and the old glass textures! [...] Connected Glass doesn't replace the vanilla glass blocks, but instead adds extra ones

The mod's page states it requires Indium, but Embeddium provides those APIs directly so it should not be necessary to add.

**Comment by MuteTiefling** [comment]
Thanks for the request! We'll have a look at it.

And this is the best place for mod suggestions. They are often discussed on Discord, but at the end of the day nothing will happen without a request here too :D
