### ISSUE TITLE
Sawmill

### ISSUE THREAD

**Issue by purrloftruth** [EnigmaticaModpacks/Enigmatica10#153]
### URL

https://www.curseforge.com/minecraft/mc-mods/sawmill

### Why would you like the mod added?

From the mod's page:
> Universal Sawmill does one thing and does it well.
> The mod adds a new Sawmill crafting station which allows you to craft any wooden items.
> The feature is fully integrated within your world with unique Villager Houses and Carpenter villager providing a seamless experience.

Essentially, this adds an equivalent to vanilla's Stonecutter block which works with wood instead of stone.

There is another mod, [Corail Woodcutter](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter), which does the same kind of thing; as far as I can tell, neither were previously used in E9.

**Comment by NielsPilgaard** [comment]
I like the idea, but I'm not fond of having to support another large recipe group :P To make this fit well into E10 would be a lot of work, I think.
