### ISSUE TITLE
MOTD does not display (stuck on 'Pinging...')

### ISSUE THREAD

**Issue by purrloftruth** [EnigmaticaModpacks/Enigmatica10#158]
### Modpack Version

1.10.1

### Describe your issue.

Carrying this over from the Discord support channel:

> I have spun up three separate E10 (1.10.1) multiplayer servers, one on a shared host (Birdflop), and two on two computers I have here at home (one Windows 11 PC, one macOS Sequoia laptop). When adding these servers to the multiplayer server list, instead of showing the MOTD, they each get stuck on "Pinging..." (they will never display the "Can't connect to server" message). For each of these servers I have tried both with the default MOTD and with changing it in the server.properties file. I've confirmed this behavior in the client on two separate computers (the ones mentioned above), and in these cases, each server can still be connected to fine by double-clicking. Notably, the MOTDs under LAN worlds do seem to show.

I originally posted this in the Discord to see if anyone had an instance of a multiplayer server where MOTDs seemed to work correctly; nobody has responded as such in several days, so I'm moving the discussion here.

Providing debug.log in lieu of latest.log as I believe it will be of more assistance.

### Latest Log

https://gist.github.com/purrloftruth/4b6f81e793f053eb64a905b1c45214fe

### Have you modified the modpack?

Yes

### User Modifications

Client:
* Disabled Embeddium
* Added Sodium 0.6.0-beta.2
* Added Iris 1.8.0-beta.5
* Added Distant Horizons 2.2.1-a
* Added Euphoria Patcher 1.4.1-r5.3

Server: no notable modifications (other than to set a MOTD).

_Confirmed the same behavior in an unmodified client._

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

purrloftruth

**Comment by NielsPilgaard** [comment]
Fixed in 1.12.0 👍
