### ISSUE TITLE
Change to Powah cable recipes and nerf to Osmium and Refined Obsidian tools/armor

### ISSUE THREAD

**Issue by Reynales** [EnigmaticaModpacks/Enigmatica10#159]
### Describe your suggestion

I am suggesting a change to the upgrade recipes of the Powah cables, perhaps even removal of the (starter) tier cables and machines throughout the mod and a nerf to the Osmium and Refined Obsidian tools/armor. 

### Why would you like this added/changed?

Because from starter to blazing it takes about 8 of the material (hardened steel/blazing crystal) to get two crafts of 12 cables each so u get 24 cables for that amount. But if you decide to upgrade from say hardened to blazing not only would u also need to spend that same amount of materials (in this case 8 blazing crystals) but you also have to craft another capacitor because you only receive 6 cables per upgrade from lower tier. So in conclusion you are spending the same amount of upper tier material and actually have to craft an extra capacitor + the lower tier cables. 
This becomes even worse when niotic tier is reached because when you craft capacitors you now only receive 1 per craft instead of 2.

Another annoying problem I have found is the fact that 2 lower tier cables result in 6 higher tier ones, so if you crafte 24 basic tier at the beginning of your playthrough and decided to upgrade them you would receive 72(12*6) cables and then if you further want to upgrade it just keeps multiplying.

In regards to the removal of the (starter) tier. The tier itself feels just extremely underwhelming since the (basic) tier exists. The (basic) tier fulfils the early game role perfectly and makes me wonder what even is the point of the (starter) tier, I feel like it just bloats the mod.

As for the osmium and refined obsidian items I think it is pretty obvious how OP they are. 
Osmium is extremely easy to get early on and the armor gives the same amount of armor and toughness as netherite (the helm even gives 1 more armor than the netherite one), the durability of the armor also is not that much worse off than netherite. The osmium tools each have 1k durability(half of netherite), the sword is as strong as a netherite sword(8dmg) and the paxel does a ridiculous 14dmg. The only downside the tools have is that the mining speed is not the greatest (being a bit slower than iron).

Refined obsidian armor and tools have about twice the durability of netherite armor and tools. The armor set gives 31 armor and 20 toughness while netherite is 20 armor and 12 toughness. The sword does 12 dmg while the paxel does a whooping 17. They mine slightly faster than netherite as well. Now to be fair you do need the capability to mine obsidian, a few diamonds and some mekanism machines to make refined obsidian but I still think the difficulty of obtaining it is quite low for the extremely high stats that it has.

**Comment by MuteTiefling** [comment]
I agree the starter tier leaves a lot to be desired. I'm not 100% sure I want to go through the trouble of removing them again though. 

That said, I think the cable issue can be handled by simply removing the upgrade recipe and replacing it with a way of recycling old cables. This way you're able to re-use those materials for whatever you like.

**Comment by MuteTiefling** [comment]
Also, as for Osmium and Refined Obsidian, even though we've nerfed them in the past, I think this pack has enough armor alternatives that offer benefits beyond simple armor, that they're probably fine.

Just Dire Things adds a suite of armors with special features. PneumaticCraft, Mekanism, and Ars Nouveau also all offer modular armors of some description. I think it's safe to say the actual armor value is among the least important features when comparing what all of these armor sets can do.

**Comment by NielsPilgaard** [comment]
I agree, let's keep it OP this time around :P

**Comment by MuteTiefling** [comment]
Gonna mark this as Won't Fix for now since most of this isn't going in.

That said, the powah cables will be getting a change as per #160 which I think generally resolves the issue that raised this discussion.
