### ISSUE TITLE
Torchmaster

### ISSUE THREAD

**Issue by purrloftruth** [EnigmaticaModpacks/Enigmatica10#162]
### URL

https://www.curseforge.com/minecraft/mc-mods/torchmaster

### Why would you like the mod added?

Previously in E6 and E8.

From the mod's CurseForge page:

> Adds a special torch which prevents mob spawning in a configurable radius.

Provides several blocks (Mega Torch, Feral Flare Lantern) handy for preventing mob spawns in large bases or without placing down large amounts of individual torches.

As this mod was not in E9, I'm not sure if you all had switched to something else that does the same job and I'm just unfamiliar with it or not.

**Comment by MuteTiefling** [comment]
There is at least one option in the pack, ars nouveau's sanctuary ritual acts like a mega torch.

PNC also has a very similar feature to the feral flare lantern in the kerosene lamp.

They'd be worth checking out in the meantime.

Probably no harm adding this though.

**Comment by flece** [comment]
my 2 cents: pls dont add the mod...so ppl check out other options. But Provide an Quest that hints to Ars / PNC
i realy like the Megatorch but the Pack is easy eneugh.

btw: can i have Ars Source as Fuel for Kerosinlamp like E9:E xD

**Comment by MuteTiefling** [comment]
Need starbuncle mania before we can do liquid Source anything :D

**Comment by NielsPilgaard** [comment]
I'm thinking we won't add this, to allow other less easy options to shine 😊
