### ISSUE TITLE
I'm Fast Mod

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica10#163]
### URL

https://www.curseforge.com/minecraft/mc-mods/im-fast/files/5768932

### Why would you like the mod added?

Does what Too Fast did, but Too Fast is not ported. I have a feeling it won't be since 1.21.2 is adding a gamerule for this, this mod will be good as a holdover in the interim.

**Comment by DoomSquirter** [comment]
ur stealing mah issues boo!  :(  I was going to get around to it! :P 

anyways, I have it running on my server and it definately gets rid of the rubber banding

**Comment by HeatherComputer** [comment]
Do we even know if 1.21.2 will be viable for a pack update?
