### ISSUE TITLE
Ars Ocultas

### ISSUE THREAD

**Issue by PentBeear** [EnigmaticaModpacks/Enigmatica10#165]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-ocultas

### Why would you like the mod added?

This mod integrates occultism spirits with Ars Nouveau features. Notably, the ability to put spirits into Containment Jars and have them still be used with added item piping support. This was discussed in the discord server [^1]

Notes:
- This mod is not updated to 1.21.1 yet (only 1.21)
-  It is unknown when this mod will be updated
[^1]: https://discord.com/channels/195234321836146688/1289537897891889185/1293691830315122781

**Comment by HeatherComputer** [comment]
Probably worth noting that all 1.21 mods should work on 1.21.1.

A bigger concern is whether or not it'll work with the latest ars / occultism versions.

**Comment by MuteTiefling** [comment]
They've marked it for 1.21.1 now :D

And it does seem to be working fine so far. Can shove spirits in jars and they keep working as expected.
