### ISSUE TITLE
YUNG's Better Mods

### ISSUE THREAD

**Issue by Koishukaze** [EnigmaticaModpacks/Enigmatica10#167]
### URL

https://www.curseforge.com/members/yungnickyoung/projects

### Why would you like the mod added?

Considering YUNG's Better Mods were recently updated to 1.21.1 I feel they'd add a bit more variety to the world

(unsure how to link multiple mods of the same type)

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion, we'll think about it 👍
