### ISSUE TITLE
Theurgy/Occultism books large minimap

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#17]
### Modpack Version

1.2.0

### Describe your issue.

With the Theurgy and Occultism books, when you click on an item the mini map which is usually in the circle becomes a lot bigger.

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/cfedcc9b-4962-4aa6-b1a4-22747fd9c483)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by SupaJordy** [comment]
It returns to normal when you close the item.

**Comment by NielsPilgaard** [comment]
Boy that is strange, thanks for the report.

@klikli-dev got a weird one for you :D

**Comment by NielsPilgaard** [comment]
Journeymap indeed, I'll see if this is fixed in the latest journeymap update 👍

**Comment by NielsPilgaard** [comment]
Nope not fixed in `journeymap-neoforge-1.21-6.0.0-beta.13`

**Comment by Kevin-Marsh** [comment]
This should be fixed in Journeymap beta 14 that was released today.

**Comment by klikli-dev** [comment]
Fantastic, thanks!
