### ISSUE TITLE
Cobblegen Galore [tiered customizable block generator]

### ISSUE THREAD

**Issue by Thiana** [EnigmaticaModpacks/Enigmatica10#171]
### URL

https://legacy.curseforge.com/minecraft/mc-mods/cobblegen-galore

### Why would you like the mod added?

Some decorative blocks are just too rare in worldgen to reasonably manually collect thousands+. 

Serves as an alternative to https://legacy.curseforge.com/minecraft/mc-mods/cobblegenrandomizer which was in E6E. Unlike CGR it can also be configured to consume the 'source' blocks, ie lava when making obsidian.

Please start with soapstone ;)

**Comment by MuteTiefling** [comment]
Looks like working with this will be quite easy. Looks good to me

**Comment by Thiana** [comment]
Thank you :)
