### ISSUE TITLE
Nature's aura book is in @patchouli mod's jei but has no recipe but book works fine if cheated in

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#176]
### Modpack Version

1.11

### Describe your issue.

NA book needs a recipe

it works and is in jei but there's no recipe attached

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report, I've relayed it!
