### ISSUE TITLE
Ars Énergistique

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica10#178]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-energistique

### Why would you like the mod added?

Possibly interesting mechanics between Ars and AE2.

**Comment by MuteTiefling** [comment]
Could be fun. I do recall there being a rather annoying interaction with it though that I'd hope has been improved... namely interfaces constantly sucking in Source from nearby jars relays with no real way to prevent it other than keeping them far away.

Will take a look later. I recall them at least acknowledging that with the idea of a separate source interface to control for it.

**Comment by NielsPilgaard** [comment]
I vote yes :D

**Comment by MuteTiefling** [comment]
Ok, so they did change blocks around so you have a dedicated block to send source into the system, as opposed to using an interface. 

However, it's currently crashing when you use it. So... Voting yes, but it needs to fix this first. Doesn't do much good for source storage if you can't get source in/out. 

https://github.com/62832/ArsEnergistique/issues/27

**Comment by 62832** [comment]
> Doesn't do much good for source storage if you can't get source in/out.

I would just like to clarify that the Source Converter, which you reported that issue for, has nothing with source _storage_ but is instead used to convert source into AE energy for the network itself to use to power itself. Still, I'll make sure to investigate later today.

**Comment by MuteTiefling** [comment]
Ah, my misunderstanding there. I couldn't bind anything to the ME source jar so I assumed that was related, but upon retesting that was likely due to the other block erroring out; the ME source jar works fine this morning.

**Comment by MuteTiefling** [comment]
Looks like we're good to go on this! Updated version has this fixed.
