### ISSUE TITLE
Foliot crusher not crushing ores

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#19]
### Modpack Version

1.3.0 I forked the repo and I'm using the most recent develop branch

### Describe your issue.

Summoned a Foliot crusher but they di not pick up raw ores. If I open the GUI and place ore in inventory slot it just drops unto the ground.
![2024-07-04_06 47 08](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/25380281/cc5dcd4e-0577-48c5-8005-4e11d2251550)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by MuteTiefling** [comment]
Thanks for the report. These recipes are currently broken due to an error in kubejs. It's been reported and pending a release to fix it.

**Comment by MuteTiefling** [comment]
https://github.com/KubeJS-Mods/KubeJS/issues/293
