### ISSUE TITLE
Evilcraft entangled chalice has no recipe in EMI but is craftable

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#190]
### Modpack Version

1.11.1

### Describe your issue.

Evilcraft entangled chalice has no recipe when you click it in emi but if you look at the book and use the recipes therein, it crafts fine.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
Thanks for the report! This appears to be fixed in Dev.

**Comment by DoomSquirter** [comment]
you're welcome.  I only require tree fiddy for my time.
