### ISSUE TITLE
Ars Nouveau's Flavors & Delight

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica10#198]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-nouveaus-flavors-delight

### Why would you like the mod added?

Fun little mod to add some food variety, integrating Ars Nouveau with Farmer's Delight

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion. Do you know how it compares to [Ars Nouveau Delight](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau-delight)?

**Comment by SeooY** [comment]
Ars Nouveau's Flavors & Delight is much more developed currently. The concept is similar, but this is all Ars Nouveau Delight has implemented so far:
![image](https://github.com/user-attachments/assets/171c2ee7-d6f4-4f6c-b7a8-c8360c6fa796)
5 storage blocks and 4 foods, that's it. The foods are nothing special either.

Flavors & Delight has those 5 storage blocks, but it also implements custom drops from Ars' mobs, custom potion effects on the food, feasts, and has much more content in general:
![image](https://github.com/user-attachments/assets/c94b7ae8-3ec9-42c1-96bc-854bac4aab83)
