### ISSUE TITLE
strange server crash happening now

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#199]
### Modpack Version

1.12.0

### Describe your issue.

so, playing on a server with one other person

whenever they use /home from my base to theirs or a couple other interactions, the server crashes
because of the other bug #185, it just halts and requires manual intervention to continue

someone can leave the server while the other is still on and the crash happens

the crashlog is not very attributable to anything.  there's like one mention at some point towards the end of journeymap.  but that's it.  

when server comes back, everything's fine.  I can tp to their base, mine, all the dimensions, back again, no issues

but the most reproducible is when I'm not on server, they tp to my base, wait 1-2 minutes then /home and it crashes

every crashlog is similar to one attached

client side gives you nothing.  message is as if you just quit server.  no kick message. nothing.

### Crash Report

https://gist.github.com/DoomSquirter/542f8ea742741ceda4737b66cae3ebff#file-crash-2024-11-04_02-50-37-server-txt

### Have you modified the modpack?

Yes

### User Modifications

added extended ae 2 weeks ago but crash started happening recently.  

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report. That's an annoyingly un-specific crash :P

@MaxNeedsSnacks Hey 👋 Got a possible FTB Essentials bug here, not likely though tbf 😂 can you infer anything from the trace?

**Comment by DoomSquirter** [comment]
the thing that is driving me nuts trying to figure this out is that it's mostly centered around the other person and not me so it seems like it's player related

I deopped myself and spent a couple hours using /home, /warp, waystones to go to either bases, nether, end, other locations in the overworld.  Nobody on server but me, a normal deopped person and nothing happened.  I exited the server a few times and nothing.

and that trace doesn't help since nothing is called out specifically.

**Comment by NielsPilgaard** [comment]
I guess it's an entity near your friend's base?

**Comment by DoomSquirter** [comment]
nope.  or it'd affect me too

tbh at this point I'm not sure

I need to find out where he's putting his /home
maybe just going to his base isn't enough.  I need to show up at that same spot to cause it

but then that doesn't explain the same crashlogs when he is in my base and I quit server or he quits server while in my base but not when I'm alone on server and quit and it doesn't crash

it's concentrated lunacy

**Comment by DoomSquirter** [comment]
that is a really excellent point 

we will try testing again next time they are around.  see if the same things they do to crash, if I can do them instead

it's just really a pain to diagnose since we also have that bug where any crash leads to a stuck instance cause of the inventory sorter mod from cpw.

**Comment by DoomSquirter** [comment]
did not get a chance to test anything but to sum up latest crash

other person logged into server, was on for 4 or 5 hrs but I had to go eat

when I came back we talked but they were leaving

they quit server and server crashes
they were in their base, I was in mine

there's absolutely nothing I can think of that would cause this

same exact set of errors

https://gist.github.com/DoomSquirter/b3ba29ed45d723a2b7d46ef7bba09945

not sure wtf we can do to pursue this

**Comment by Kanzaji** [comment]
I have a one theory, which might be useful to eliminate - smooth chunks. Maybe ya are somehow triggering some edge-case where it's crashing 😅?

Also replying to my previous idea - completely forgot the fact it was happening with only the other person on the server when I was writing it :P 
=

**Comment by DoomSquirter** [comment]
yeah I'm really at a loss trying to diagnose this when it revolves around one person and not the other

I'm going to get them to show me all of their baubles / armor.  anything that defines them as different from me

we can get them to drop everything and I destroy their player.dat and see if it makes the problem go away but then they'll lose a bunch of stuff stored there

there really isn't much to do here.  a third person joining to see if they get the same issue I guess.  I'm open to suggestions

I don't think I can run a debugger cause it's hosted and I don't have shell access or anything.

**Comment by DoomSquirter** [comment]
so it turns out they aren't crashing anymore.  they haven't been playing but yeah, crashes are gone

All I have done to the server since then was remove the cpw inventory sorter so it's pretty much guaranteed that was causing the crash (as well as stopping the server when it did crash and keep it from rebooting)

Closing issue.
