### ISSUE TITLE
Waystones don't have a texture assigned when breaking

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#2]
### Modpack Version

1.0.1

### Describe your issue.

When mining a waystone, the particles from breaking it do not have a texture.

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/65d82de8-0cba-44eb-87ce-9949e789cd84)

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/5be7a07c-6305-4a5b-8272-80f027db2abb)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by MuteTiefling** [comment]
Thanks for the report! I've relayed the issue.
