### ISSUE TITLE
Recurring freezing with journeymap

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#20]
### Modpack Version

1.3.0

### Describe your issue.

I've been happily playing e10 but when updating to 1.3.0 the game started freezing every 4 seconds or so.
I downloaded a new instance of e10 1.2.0 and created a new world. Again, worked without issue but when I update to 1.3.0 I get the freezing every few seconds.
I created a spark profile https://spark.lucko.me/4kEqk7gmBH ) and the handy folks in the Enigmatica support channel suggested that JourneyMap might be the problem.
After disabling JourneyMap, I no longer have the issue.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by NielsPilgaard** [comment]
Thanks for the report. 

I can't locate the issue through the profile, @Darkere can you?

**Comment by Darkere** [comment]
Journeymap is throwing an error loading textures which is taking a long time. There could be something in the log showing which entity or block is causing that?

**Comment by NielsPilgaard** [comment]
@SupaJordy could you provide your latest.log please?

**Comment by NielsPilgaard** [comment]
I downloaded a fresh client and had the same behaviour. My log had rendering issues that came from Simple Discord RPC.
@SupaJordy please try removing the mod `Simple Discord RPC` and see if that resolves the issue.

**Comment by NielsPilgaard** [comment]
Oh nvm, I was encountering this: https://github.com/hypherionmc/simple-rpc-public/issues/88

We still need that log of yours :D

**Comment by NielsPilgaard** [comment]
We would need the log from while it's happening I'm afraid 😅

**Comment by SupaJordy** [comment]
Weird thing, I downloaded a new instance of 1.2.0 and instantly updated it to 1.3.0, then logged in and created a new world. I didn't get the freezing issue.

I then downloaded another 1.2.0 instance, created a new world and then updated to 1.3.0. In this instance the freezing issue happens.

Here is the latest.log for the world with the issue.

[latest.log](https://github.com/user-attachments/files/16109999/latest.log)

**Comment by NielsPilgaard** [comment]
Could you provide a log where the issue is not present?
I'd like to know if this line appears there as well: 
`[05Jul2024 13:53:14.825] [Render thread/WARN] [oshi.util.platform.windows.WmiQueryHandler/]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile`

**Comment by SupaJordy** [comment]
Sure.

This is the log from the world where I have disabled journeymap and am playing without issue: 
[latest.log](https://github.com/user-attachments/files/16112909/latest.log)

And this is the log from the world I created on 1.3.0 instead of updating. I've only run about on this world long enough for me to be satisfied that the issue wasn't happening.
[latest.log](https://github.com/user-attachments/files/16112912/latest.log)

**Comment by NielsPilgaard** [comment]
Yay it doesn't \o/ I'll try to relay to Journeymap

**Comment by NielsPilgaard** [comment]
They might want your `journeymap/journeymap.log` log aswell 😅

**Comment by NielsPilgaard** [comment]
That was quick, thanks! That log has much more info 😅

**Comment by NielsPilgaard** [comment]
Could you try with the latest Journeymap please? beta.14 :)

**Comment by SupaJordy** [comment]
I removed journeymap 13 jar from the mod folder and added the neoforge journeymap 14 jar:
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/b2a3ce79-08fb-4952-8014-a01132d5aad5)

Launched e10 and loaded the world but I still get the freezing every 3-5 seconds on this version.

Spark profile: https://spark.lucko.me/EQktnoI5IX
latest.log:
[latest.log](https://github.com/user-attachments/files/16117031/latest.log)
journeymap log:
[journeymap.log](https://github.com/user-attachments/files/16117032/journeymap.log)

**Comment by NielsPilgaard** [comment]
Perfect, thank you 😊

**Comment by mysticdrew** [comment]
Have you added any mods other than what's in the pack, and is anyone else having this issue?

I'm the journeymap dev, this issue is really odd.

**Comment by NielsPilgaard** [comment]
I have similar entries in my log, but no lag:

https://gist.github.com/NielsPilgaard/00055879ff6ce1c8b117e300cbce05fc

The log appeared after I encountered creepers from the [Creeper Overhaul mod](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul).

**Comment by mysticdrew** [comment]
Oh interesting, thanks. I'll have to look into that mod.

**Comment by mysticdrew** [comment]
[jm.zip](https://github.com/user-attachments/files/16117452/jm.zip)
I had had to add this to a zip so i could upload it to github. 

Anyways, can you give that a try please? Also after trying it can you provide your journeymap.log, I added some extra logging to see what is going on and a potential fix.

**Comment by SupaJordy** [comment]
@mysticdrew Other than switching to JourneyMap 14 beta, this is just a fresh install of e10.

I'll use that file and report back.

**Comment by SupaJordy** [comment]
I removed the JourneyMap 14 beta jar and replaced it with the one in your zip file. Oddly, it seems to work without the lagging issue.

Journeymap log:
[journeymap.log](https://github.com/user-attachments/files/16117470/journeymap.log)

**Comment by mysticdrew** [comment]
Thanks, the logs don't have much. Can you play for a while and uploada new log later please? I need to see what entities are causing it.

**Comment by SupaJordy** [comment]
No problem. Not sure when I will get to do this but will upload when I can. Just to point out, the issue DIDN'T seem to be happening with the jar in that zip file.

**Comment by mysticdrew** [comment]
I understand that it's not happening. Because i kinda fixed it half way. But you won't get entity iicons for some entities.

**Comment by SupaJordy** [comment]
@mysticdrew Ran around for 15 minutes or so.

[journeymap.log](https://github.com/user-attachments/files/16124280/journeymap.log)

**Comment by hypherionmc** [comment]
> Oh nvm, I was encountering this: [hypherionmc/simple-rpc-public#88](https://github.com/hypherionmc/simple-rpc-public/issues/88)
> 
> We still need that log of yours :D

We're pushing out an update for craterlib in the next day or two to address this issue. We finally found the cause of it, and it spans back several versions of Simple RPC. As far as we are aware, it only affects DIRECT connections and lan connections.

**Comment by NielsPilgaard** [comment]
> We're pushing out an update for craterlib in the next day or two to address this issue. We finally found the cause of it, and it spans back several versions of Simple RPC. As far as we are aware, it only affects DIRECT connections and lan connections.

I saw, thank you 👍
