### ISSUE TITLE
Advanced AE (maybe Extended AE as well)

### ISSUE THREAD

**Issue by Yamijiro** [EnigmaticaModpacks/Enigmatica10#203]
### URL

https://www.curseforge.com/minecraft/mc-mods/advancedae ; https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider

### Why would you like the mod added?

These mods add a lot of depth to AE2 by adding better/more interesting auto crafting capabilities, materials, machines and equipment like an upgradable armor set.

**Comment by MuteTiefling** [comment]
Duplicate #62
