### ISSUE TITLE
invtweaks refoxed - replace inventory sorter

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#206]
### URL

https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-refoxed

### Why would you like the mod added?

maybe replace the current inventory sorter mod with this one

hopefully it doesn't have the same problem that's causing #185

is this the one that was in there previously before inventory sorter?

I'm just trying to find alternatives here

**Comment by NielsPilgaard** [comment]
Let's try 👍

**Comment by MuteTiefling** [comment]
https://github.com/JDKDigital/InvTweaksRefoxed/issues/16

**Comment by NielsPilgaard** [comment]
Oof good catch. Does sorting in a filter do anything?

**Comment by MuteTiefling** [comment]
Doesn't seem to? But this button shows up absolutely everywhere

**Comment by NielsPilgaard** [comment]
Alright, it's gonna be a pass from me then 😬
