### ISSUE TITLE
E10: Genetics Resequenced - Water Breathing gene not working

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#207]
### Modpack Version

1.12.0

### Describe your issue.

After successfully giving myself the Water Breathing gene I jumped into an underwater cave and promptly drowned. Tested in more open water and it is not giving the water breathing effect. Others on the E10 channel confirmed the same.

### Crash Report

NA

### Latest Log

NA

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by MuteTiefling** [comment]
Thanks for the report, I've relayed the issue!

**Comment by Drytchnath** [comment]
Per Boo this has apparently been fixed by the dev!
