### ISSUE TITLE
Inventory Profiles Next

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica10#209]
### URL

https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/5880542

### Why would you like the mod added?

Another possible replacement for inventory sorter since that mod has an issue with shutting down properly on host services still.. and the last one we tried was a no-go.. seems to be more similar to the sort buttons we have in e2e with different sort directions and such.

**Comment by NielsPilgaard** [comment]
@wasdspace Any chance you can elaborate on your downvote? Might save me quite a bit of time :P

**Comment by NielsPilgaard** [comment]
The issue tracker link sending me to Discord is a red flag 😬

**Comment by theboo** [comment]
Yeah that is weird... The *source" link sends you to the actual repo tho and it has an issue tracker that seems active in the last week or so? So at the very least it's not discord only haha 

Am curious what the downvote is for as well, I tested it a bit and it seems to work as expected? Mod has a lot of pre-ignored screens, and it's just a hotkey away to add the GUI you're in to the ignore list, no looking through logs..

Also, I'm perfectly happy with cpw inventory sorter, just trying to find an option for the users using host services having hangs in their auto restarts...(On my windows machine, I get the same error on restart they get, it just doesn't hang)

**Comment by Thiana** [comment]
IPN is what I use without issue in almost every modpack I play. You'll definitely want to customize the defaults though because they make the screen a bit busy. ie, hide the profiles button at the bottom of the inventory screen and move the settings/gui move buttons so they dont overlap with the ftb ones.
