### ISSUE TITLE
Get KubeJS client script errors

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#22]
### Modpack Version

1.3.0 develop branch

### Describe your issue.

When I load the pack in Prism Launcher I get a KubeJS script error and pack will not load. I uninstalled, and synched the fork again and still get the error. I looked at my forked repo and all the scripts looked  identical to the original develop branch. I am using NeoForge  21.0.59 beta mod loader.

### Latest Log

https://gist.github.com/calog3no/882f336f0c4312fe54312719f976aba5

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by MommyHeather** [comment]
what on earth are you trying to do with that script tag there

**Comment by calog3no** [comment]
I have made a fork of the repo and have cloned it using Git bash to my install. I have been updating using the upstream function and this is the first time receiving an error after updating. I will attach the log here
[client.log](https://github.com/user-attachments/files/16117116/client.log)

**Comment by NielsPilgaard** [comment]
I fixed that bug a few minutes ago 👍
