### ISSUE TITLE
FTB buttons in the Inventory Screen are missing

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica10#220]
### Modpack Version

1.13.0

### Describe your issue.

Installing a brand new instance of version 1.13.0 results in all of the FTB buttons (from FTB Maps, FTB Ranks, etc) to be missing from the inventory screen.
![image](https://github.com/user-attachments/assets/c96e01f5-2aea-45c1-8bda-00b29c462283)
The issue does not happen if you update from an earlier version.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

SeoY

**Comment by MuteTiefling** [comment]
Kinda seems like our default isn't being copied out anymore?

**Comment by SeooY** [comment]
It is, the default has the FTB sidebar disabled currently:
https://github.com/EnigmaticaModpacks/Enigmatica10/blob/ae87e57b16781d8da3a04621b4231930752b97ad/defaultconfigs/ftblibrary/ftblibrary-client.snbt#L64-L66

**Comment by NielsPilgaard** [comment]
I can't believe I missed that 😅 thanks, fixed in-dev!
