### ISSUE TITLE
Structure finder

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#223]
### URL

https://www.curseforge.com/minecraft/mc-mods/structure-compass

### Why would you like the mod added?

Make ppl that wanna find a specific structure lag less a server or make it less frustrant.
Yes i know that could make exploration less of a thing, but imagine the situation where you wanna find a trials chamber for hours and cant find and gets frustrated because you can only play for 3 hours :> (yes work soks)
also yes i know nature's compass is a thing, and it helps a lot, but a lot of structures are not biome dependent

and if there's another mod in the pack that does that i would love to know

**Comment by flece** [comment]
Offtopic: Trialchambers are easy to find by using Journemap and change layer to +1 or similar just play wiht the layers. sometimes layer are not generated and u need to ask Journemap to generate that layer.

Ontopic: we already have a way to find structures with the Mod "Ars Additions" with the item "Wayfinder"
In E10 this gizmo is easy to build and can find you 16 different Strcutures.

**Comment by theboo** [comment]
Also, wayfinder/structure ritual(barely need any ars to do this, don't even need source) is completely recipe based, so recipes can be added for some of the modded structures that don't currently have recipes

**Comment by MuteTiefling** [comment]
Some recipes have already been added to it, in fact. :D

**Comment by criscky** [comment]
good to know, i had no idea some ars addon had that, offtopic with this suggestion, but there's any "rain shield" kinda of block, not one to stop the rain, just deacivate the rain effect and sounds in a certain area?

**Comment by MuteTiefling** [comment]
Not exactly no. Several options for stopping rain but I can only think of 2 close to what you're looking for.


1. A glass roof at build height
2. Change the biome to something that can't rain. Evil craft lets you modify the biome.

**Comment by NielsPilgaard** [comment]
Since we have this mechanism already, it's gonna be a nope 😊
