### ISSUE TITLE
The various Experience types aren't intercompatible

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#224]
### Modpack Version

1.13.0

### Describe your issue.

The bottle 'o enchanting recipes in the Industrial Foregoing Dissolution Chamber and the Enderio Tank Filling use the mod specific experience type instead of the #c:experience tag. This means that experience from other mods aren't valid for these recipes. Swapping them to the tag instead should fix it.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
https://github.com/Team-EnderIO/EnderIO/issues/902

**Comment by MuteTiefling** [comment]
Thanks! I've relayed this. From memory we can't fix ourselves, I think it doesn't accept tags for fluids in this machine.

I'll check in on the eio one later to see if we can fix that one ourselves.
