### ISSUE TITLE
Tiny coal unification

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#225]
### Describe your suggestion

There are 2 types of tiny coal in the pack, it doesnt bother that much, but it would be cool if you can unify them, i think one is from actually additions and one from utilitarian

### Why would you like this added/changed?

just add the tiny coal to the unify.json of almostunified, and declare which mod has priority for unification

just more info i'm using latest beta 1.13.0

**Comment by MuteTiefling** [comment]
Thanks for the report! I'll get that fixed up soon
