### ISSUE TITLE
[Charcoal block] Unify the two charcoal blocks

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#229]
### Describe your suggestion

There are 2 charcoal blocks in the pack, mekanism and just dire thing

### Why would you like this added/changed?

unify the two so there's only one

**Comment by MuteTiefling** [comment]
Thanks for the report! 

That's airway covered by https://github.com/EnigmaticaModpacks/Enigmatica10/issues/225

**Comment by criscky** [comment]
see thanks didnt saw you also coved the block form as well

**Comment by MuteTiefling** [comment]
Block form, yes, but apparently we didn't have JDT in the unification list, so I'll get that changed here.
