### ISSUE TITLE
Modern Dynamics

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#231]
### URL

https://www.curseforge.com/minecraft/mc-mods/modern-dynamics

### Why would you like the mod added?

More pipe options are great, also bias opnion but since modern industrialization is in here would make totally sense to have modern dynamics, also kinda new mod for 1.21.1
yes it's basically thermal dynamics but still

**Comment by NielsPilgaard** [comment]
Looks nice, but the lack of response to bugs on their issue tracker makes me nervous 😅

**Comment by Kevin-Marsh** [comment]
Modern Dynamnics are run by the same people that run Applied Energistics and Modern industrialization. It is a fairly reliable mod.
