### ISSUE TITLE
Gateways to Eternity

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#232]
### URL

https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity

### Why would you like the mod added?

Just a little nice way to get mobs to spawn without having a spawner or such, also gives a little challenge if you want certain loots, basically make gateway of something, defeat wave, get reward, complete all gateway gets rewards.
it kinda remind me of tower defense games for some reason
You guys can also create custom gateways for anything

**Comment by BMK2** [comment]
This would be nice to have. I have a decent player base that likes to pursue magic mods purely to see how much damage they can do with their spells. Having this mod would let them test those limits without having to attack other players (aka me in my Mekanism suit)
