### ISSUE TITLE
[TierUp Powah]

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#234]
### Describe your suggestion

Basically what i propose is a recipe or way to tier up powah cables and ender gates

### Why would you like this added/changed?

Mostly because those items becase obsolete as the game progress, like i have some starter cables that i made for simple stuff when i was into a lot more magic, and there's no use for those as i have access to better cables
what i dont propose is removing the ability to craft those items without tier up, but having a tier up option would be great, and make the starter items not so "useless" anymore
and yes i know there are some machines that dont need that much power, but powah cables cant connect between tier, and eventually those machines will need more power
Also mekanism cables have tier up system

**Comment by MuteTiefling** [comment]
The recycling recipes we added were put in place to offer you a way to make those old cables useful.

![image](https://github.com/user-attachments/assets/b5ddfa67-66ef-4c33-9a52-e0dfac642d01)
![image](https://github.com/user-attachments/assets/5413a2c6-888a-4063-ab0e-301b4d5c4226)

Scrap your old cables and turn those components into something else. Its very likely you'll be able to use them in an energy cell or in upgrading a generator. 

As for ender gates, they're pretty much always useful. They'll go on any tier of machine or cable, so there's no concern there, and you can use them to power low draw machines directly.
