### ISSUE TITLE
Pretty Pipes

### ISSUE THREAD

**Issue by Ellpeck** [EnigmaticaModpacks/Enigmatica10#236]
### URL

https://www.curseforge.com/minecraft/mc-mods/pretty-pipes

### Why would you like the mod added?

Very cool mod, it was in your packs previously already! Also it has mid-game item storage with requesting and on-demand autocrafting (which now supports the vanilla crafter yay!!), plus it's pretty cute. @Motoko already approved it 😎

**Comment by MuteTiefling** [comment]
We should add https://www.curseforge.com/minecraft/mc-mods/pretty-pipes-fluids at the same time, honestly

**Comment by criscky** [comment]
i really like that as some early game "storage management" of course, you can just jump into ae2, but "no power required" is fun as well

**Comment by MuteTiefling** [comment]
I really enjoyed them in e6, tbh. I know it's not everyone's favorite since it can drop items on the ground, but as a cheap early pipe they work great.

**Comment by MuteTiefling** [comment]
Minor issue pending for PP Fluids: https://github.com/Quarris/PrettyFluidPipes/issues/14
