### ISSUE TITLE
Universal Cable Facades

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica10#237]
### URL

https://www.curseforge.com/minecraft/mc-mods/cable-facades

### Why would you like the mod added?

Looks very promising. Will be testing it out soon to see how well it works.

**Comment by criscky** [comment]
i saw someone saying it works on laserio
just saying it could be pretty cool
as a side note, i saw a commit about performance stuff, so might be good check for that

**Comment by BMK2** [comment]
I would love this! It would allow me to set up "mystical" mech builds for my players

**Comment by Leclowndu93150** [comment]
hey btw this is in 1.20 and 1.19 too :P
