### ISSUE TITLE
Open Sesame (double-doors opening in-sync)

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#240]
### URL

https://www.curseforge.com/minecraft/mc-mods/double-doors

### Why would you like the mod added?

Dear god, please some double door support, when i saw my double doors not opening both when i open one, made me question everything i knew about modded minecraft

if not that mod, please some other

**Comment by NielsPilgaard** [comment]
I'd rather not add that mod, although I do want it's functionality 😂 do you know of any alternatives?

**Comment by HeatherComputer** [comment]
Is there any particular reason for not wanting this mod?

**Comment by NielsPilgaard** [comment]
We've used a Serilum mod in a previous modpack that had a negative impact on performance, and I'd rather not risk making that mistake again.

**Comment by NielsPilgaard** [comment]
Woops closed prematurely, I hope there's another mod that offers this 😅

**Comment by HeatherComputer** [comment]
Ahh, understandable

**Comment by Thiana** [comment]
https://modrinth.com/mod/open-sesame ? I've not used it myself though so no idea how well it works.

**Comment by NielsPilgaard** [comment]
> https://modrinth.com/mod/open-sesame ? I've not used it myself though so no idea how well it works.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/711464b7aa8bf1c594461a36dca4057c09eac668dc2bb9e441a7cc9a9317c668/68747470733a2f2f63646e2e6d6f6472696e74682e636f6d2f646174612f7534306652586c4b2f336663383136313837356232666633336663393534323839613932336164333139636633326334322e706e67"><img alt="" height="14" src="/favicon.ico"> Modrinth**[Open Sesame - Minecraft Mod](https://modrinth.com/mod/open-sesame)**Open doors together; Open Sesame!
> 
> https://www.curseforge.com/minecraft/mc-mods/open-sesame

Works like a charm, thanks!
