### ISSUE TITLE
Discord presence says Enigmatica 9

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#242]
### Modpack Version

1.13.0

### Describe your issue.

![image](https://github.com/user-attachments/assets/c7d136f7-5fcb-4487-841f-289605acfdf7)
not much to say

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

criscky

**Comment by NielsPilgaard** [comment]
Thanks for letting us know, fixed in-dev 👍
