### ISSUE TITLE
[Suggestion] AdvancedAE

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#245]
### URL

https://www.curseforge.com/minecraft/mc-mods/advancedae

### Why would you like the mod added?

This mod provides QOL additions to Applied energistics.

- Adds a Reaction chamber that allows you to produce resources like certus, fluix, charged certus with the ability to dupe them similar to how LazierAe2 used to function.

- Adds a Quantum Crafter that allows you to more easily automate crafts like recursive duplication (smithing table etc)

- Adds a set of Quantum Armor that is able to interface with your AE system and provides some nice features like auto feeding, crafting blocks on demand to stock in your inventory

- Adds a quantum computer multiblock that is meant to replace having a lot of individual crafting CPU's. A single Quantum Computer can perform as many tasks as you ask of it provided it has enough storage space.

**Comment by criscky** [comment]
just a fyi
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/62
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/203

**Comment by Kevin-Marsh** [comment]
These previous issues are no applicable since they are mostly focusing on Extended AE whereas this is Advanced AE.

**Comment by MuteTiefling** [comment]
I've spent some time poking through it here in creative and I'd say it's mostly leaving me scratching my head at some of the choices... It's not quite so egregious 'x but more' as extended was, but there is a good deal of that going on.

I'd say I'm more ambivalent on this one than anything.

**Comment by NielsPilgaard** [comment]
Let's give it a shot :)
