### ISSUE TITLE
[Suggestion] Applied Flux

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#246]
### URL

https://www.curseforge.com/minecraft/mc-mods/applied-flux

### Why would you like the mod added?

Allows AE to store and transmit flux. This allows for more complex and compact setups with the ability for providers to transmit energy into the machines they are touching.

**Comment by MuteTiefling** [comment]
I'm honestly on the fence with this one. It's certainly neat to be able to pull power through the network without a p2p, but on the other hand it's absurd how good a single cell is at storing energy >.>

**Comment by Kevin-Marsh** [comment]
The biggest advantage of Applied flux is the energy transmission but yes the storage is also op. You can limit the amount of FE stored per byte of storage in the config to reduce the capacity if you feel that it gets to be too op. You can also disable the FE cells and force the users to use storage buses hooked up to an external inventory. The mod allows players to storage bus an induction matrix for example. The main advantage of the FE cells is simply the size. They were mostly balanced against the ultimate induction cells from Mekanism cost and capacity wise.

**Comment by NielsPilgaard** [comment]
I've decreased the capacity quite a bit (65536 FE per byte)
The spelling isn't great, other than that the quality looks good, I'll add it 👍
