### ISSUE TITLE
[Sugestion] GTBC's Spellbooks

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#247]
### URL

https://www.curseforge.com/minecraft/mc-mods/gtbcs-spellbooks

### Why would you like the mod added?

Adds some new spells to Iron's spells for more variety.

**Comment by NielsPilgaard** [comment]
No issue tracker nor source code 😬

**Comment by Kevin-Marsh** [comment]
Damnnit, I missed that fact. They are active on the Iron's spells discord which is where I found it and have quite a few downlods between it and their other mod. Into the bin it goes I guess.
