### ISSUE TITLE
[Bug] C:gems/coal used incorrectly

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#250]
### Modpack Version

1.13.0

### Describe your issue.

c:gems/coal is used in the Actually additions and Ars nouveau crushing kubejs files. This tag doesn't exist and the recipe is broken.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report, I'll get that fixed up
