### ISSUE TITLE
Relics: Artifacts Compat

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#263]
### URL

https://www.curseforge.com/minecraft/mc-mods/rar-compat

### Why would you like the mod added?

Turns most artifacts into relics that can be leveled up and have some interesting secondary abilities. 

I've found that its also easier to level relics with this added, especially when using stuff like Cloud in a bottle which gains XP when double jumping.

**Comment by MuteTiefling** [comment]
After seeing some of the comments on this in discord yesterday, it really seems to make a lot of the artifacts useless. Not sure it's a good fit.

**Comment by Drytchnath** [comment]
Played with it a bit more and it's probably not a good fit, especially judging by the reactions in the discord channel. Might revisit it again if the mod devs make changes.

Closing it for now.
