### ISSUE TITLE
Ars Controle

### ISSUE THREAD

**Issue by Vonr** [EnigmaticaModpacks/Enigmatica10#264]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-controle

### Why would you like the mod added?

For transparency I'll first state that I am the author.

I think it adds quite a few neat things that makes the Ars Nouveau experience more enjoyable including new blocks with functions and a few (less useful) glyphs.

There's also a client side config to improve spellbook controls that some may like.

Note that the mod isn't particularly made to be balanced - I did try my best though, and there should be enough configs to balance the powerful stuff (mainly just the warping spell prism) to make it fit well.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion 👍 @MuteTiefling what do you think?

**Comment by MuteTiefling** [comment]
I'd have to load it up to get a feel for it. I haven't played with it before and the mod description page isn't helping me much :D

Maybe boo would have more experience with it?

**Comment by theboo** [comment]
i also havent played with it at all lol, i personally want it just for the spell crafting gui QOL changes haha.. also the warping spell prism is the only cross dimensional option for spells amongst all addons which is neat(and seemingly just *works* out of the box which is wild to me)...

The temporal stability sensor is, in theory, better than the tps block we have from utilitarian as you dont get any feedback from the ulilitarian block until tps is already below 20, whereas this block gives you feedback the closer you get to 50mspt so can helpprevent tps dipping under 20 *before* it happens..

out of the current addons we dont currently have, this is the one i was most interested in checking out!

**Comment by NielsPilgaard** [comment]
Would you mind throwing it on your server and seeing how it plays? :D

**Comment by theboo** [comment]
can do! hopefully will have internet again in the next couple days! haha

**Comment by MuteTiefling** [comment]
just popped it in my dev instance. Seems pretty solid. I'll note that the keybind swapping of glyphs doesn't appear to work well with Infinite Glyphs enabled as we have. 

The rest seems solid though, and the entries in the book are helpful.

**Comment by theboo** [comment]
haha yeah, i had a feeling about that... actually just poked them on discord to see if the numbers correspond to the current glyph slots on the screen or if they're hard coded to actual slots 1-10... sounds like it's the latter but hopefully that can be fixed!
