### ISSUE TITLE
Lithium?

### ISSUE THREAD

**Issue by criscky** [EnigmaticaModpacks/Enigmatica10#273]
### URL

https://www.curseforge.com/minecraft/mc-mods/lithium

### Why would you like the mod added?

Basically less lag, maybe
I mean you guys might need do some testing, but any reason why lithium is not in?

**Comment by NielsPilgaard** [comment]
Uhm... that's an oversight 😅

**Comment by NielsPilgaard** [comment]
This'll be removed again due to incompatibilities with some other mods 😅 Feel free to re-add it in your instance if you're not seeing issues with it ofc.

**Comment by HeatherComputer** [comment]
Ah, the true performance mod experience

**Comment by BMK2** [comment]
It doesn't appear to play nicely with Block Prints either, was crashing my client earlier today when I tried to export builds
