### ISSUE TITLE
{Suggestion} Journeymap Integration

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica10#275]
### URL

https://www.curseforge.com/minecraft/mc-mods/journeymap-integration

### Why would you like the mod added?

Adds FTBChunks and Waystone integration into Journeymap allowing you to claim and forceload chunks from Journeymap and see waystones on the map.

**Comment by NielsPilgaard** [comment]
Seems like a solid addition 👍
