### ISSUE TITLE
Candles from Occultism do not satisfy the "any candle" condition in the relevant Occultism quest

### ISSUE THREAD

**Issue by SekhetBR** [EnigmaticaModpacks/Enigmatica10#29]
### Modpack Version

1.4.0

### Describe your issue.

Just like the title says. Could be a tag issue - I think I've noticed some of those with this version of Occultism. 

The pack is really shaping up! I'm having a good time :)

If you want to see the issue in action it's right around 15:30 in the linked video where I craft them and then 16:15 when I check the quest. https://youtu.be/ld6YIYeb2rE 

### Have you modified the modpack?

Yes

### User Modifications

I did have Inventory Sorter in, which has some truly hilarious interactions with Client Sort, and also the Lighty light overlay mod. Those are both client side, though. I don't think they'd cause the above. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
Thanks for the report. We'll get that fixed up!
