### ISSUE TITLE
Armor and hunger bar still show in F1 mode

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#3]
### Modpack Version

1.0.1

### Describe your issue.

When pressing F1 to remove the overlay, the armor bar and hunger bar still show. I've been informed that this is due to the Appleskin mod and to report as a bug.

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/d3638b89-c9a0-4db1-b3f9-6c5cecaed731)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by MuteTiefling** [comment]
Thanks for the report! I've relayed the issue.

**Comment by MuteTiefling** [comment]
Seems like it might be a general issue with overlays. Disabling Overloaded Armor Bar naturally got rid of the armor overlay, but saturation was still showing in F1, even with Embeddium disabled.

**Comment by MuteTiefling** [comment]
Should be fixed next release :D We seem to be missing our usual labels too
