### ISSUE TITLE
add flat bedrock

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#307]
### URL

https://www.curseforge.com/minecraft/mc-mods/flatbedrock-chimericdream

### Why would you like the mod added?

some other mod has done this in previous packs.  not sure which mod but this is a standalone.

aware that this would only affect new world gen more than likely

**Comment by DoomSquirter** [comment]
just noticed this
https://github.com/chimericdream/flat-bedrock-fabric/issues/1

it may have generation issues with terralith.  would need to be tested first I guess

**Comment by NielsPilgaard** [comment]
Pass based on that issue I'm afraid 😅

**Comment by HeatherComputer** [comment]
It seems https://www.curseforge.com/minecraft/mc-mods/flat-bedrock suffers the same incompatibility, so I'd lean more towards this being terralith's fault
