### ISSUE TITLE
Ars Unification (unifies crush-type recipes for Ars Nouveau's Crush Glyph)

### ISSUE THREAD

**Issue by Vonr** [EnigmaticaModpacks/Enigmatica10#308]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-unification

### Why would you like the mod added?

Starting again with the disclaimer that I'm the author.

It lets Ars Nouveau steal crush-type recipes from Actually Additions, Ender IO, Mekanism, and Modern Industrialization at runtime post-KubeJS.

Just thought it might be something you'd want. Doesn't add any new content or anything.

Already tested with your existing KubeJS recipes, seems fine.

Config lets you choose the priority of other mods (recipes made for ars always takes priority) as well as blacklist certain recipes by ID.

**Comment by NielsPilgaard** [comment]
Cool idea, but as far as I can tell it removes incentive to work with multiple mods, that's not really something we want to do.
