### ISSUE TITLE
crash when loading world

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#31]
### Modpack Version

1.4.0 develop branch

### Describe your issue.

I'm not sure if this is my end or not. I have had this same crash in both prism launcher and curseforge launcher. I have done a clean install clone of my forked repo and once I start my world game crashes.

### Crash Report

https://gist.github.com/calog3no/b927cb14126bf21e79e8c35718fef0d1

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by MuteTiefling** [comment]
Unfortunately the current dev branch is a little busted due to breaking changes in neoforge and a mismatch of mods.

If you'd like to simply play, I'd recommend using the master branch for now while we get things working again.

**Comment by calog3no** [comment]
Ok, sounds good, and I have been playing the release also. If you want to close this issue, or I can close it too. I'm going to keep my fork of the repo develop branch updated and keep testing on my own. I'm excited to see this pack when it's finally released.
