### ISSUE TITLE
Add Traveler's Backpack

### ISSUE THREAD

**Issue by BMK2** [EnigmaticaModpacks/Enigmatica10#32]
### URL

https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

### Why would you like the mod added?

The modpack doesn't currently have a backpack option and this one comes with a rich set of features and looks super clean.

**Comment by MuteTiefling** [comment]
I'll have a look, though I'd kinda like to wait for Sophisticated Backpacks.

That said, you can get a pretty easy bag from Occultism (Surprisingly Substantial Satchel) without much effort. It's got 9x13 slots and opens on keybind. Might be worth a look in the meantime.

**Comment by NielsPilgaard** [comment]
I would also like to wait for Sophisticated Backpacks. Switching backpack mods is a major breaking change, which I'd like to avoid.

**Comment by flece** [comment]
> I'll have a look, though I'd kinda like to wait for Sophisticated Backpacks.
> 
> That said, you can get a pretty easy bag from Occultism (Surprisingly Substantial Satchel) without much effort. It's got 9x13 slots and opens on keybind. Might be worth a look in the meantime.

Surprisingly Substantial Satchel is rly great. pls add this as an Quest so more ppl know about this.

**Comment by MuteTiefling** [comment]
^_~ 

![image](https://github.com/user-attachments/assets/d2852c82-14f5-4a8d-8195-5c4927e06824)

**Comment by BMK2** [comment]
Closing since we're waiting for Sophisticated Backpacks
