### ISSUE TITLE
Integrated dynamics

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica10#321]
### URL

https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/all?page=1&pageSize=20&sortBy=dateCreated&sortOrder=desc

### Why would you like the mod added?

Would be nice to have this for computercraft, 2 white bits and a cable allow you to interact with inventories of blocks that don't implement the generic inventory peripheral, and by chance it looks like they made a full release for .21 just the other day.

**Comment by NielsPilgaard** [comment]
As usual I wonder if adding Integrated Dynamics is too niche, as it does require some integrating into the pack, and, like all mods, comes with a perf hit. @MuteTiefling thoughts?

**Comment by Quezler** [comment]
yeah fair, figured id at least suggest it but i can live without, its just a minor annoyance that pnc/mekanism blocks have trouble interfacing with computercraft without

**Comment by MuteTiefling** [comment]
Feels too niche and with the history of performance issues it has had, I'd rather just not.
