### ISSUE TITLE
Add Lighty

### ISSUE THREAD

**Issue by BMK2** [EnigmaticaModpacks/Enigmatica10#35]
### URL

https://www.curseforge.com/minecraft/mc-mods/lighty

### Why would you like the mod added?

You may be waiting for Light Overlay to update but might I suggest Lighty instead? I very much like the way this mod goes about giving you 3 different options for how to show you the light level of the area around you. Especially for someone who is red/green colorblind, having the carpet option makes it a lot easier to know where I need to place my lights. 
![Screenshot 2024-07-15 090109](https://github.com/user-attachments/assets/22f04f00-e12c-400c-a09b-c3f3adac2c53)

**Comment by MuteTiefling** [comment]
That does look rather nice. And it being colour blind accessible is a nice touch
