### ISSUE TITLE
enchantments can't be applied to vanilla plus tools hammers

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#37]
### Modpack Version

1.4.0

### Describe your issue.

you can't apply enchants to the hammers (nothing in emi shows up and if you put in enchanting table, nothing to pick from)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

DoomSquinter

**Comment by MuteTiefling** [comment]
Yeah, these things are missing basically every tag they would need to function properly.

**Comment by MuteTiefling** [comment]
@
