### ISSUE TITLE
break crafting station and get nothing back

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#38]
### Modpack Version

1.4.0

### Describe your issue.

you break crafting station with axe and get nothing in return

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

DoomSquinter

**Comment by MuteTiefling** [comment]
Seems to already be fixed by updating the mod. Working fine in dev.
