### ISSUE TITLE
Sal Ammoniac Accumulator won't accept water

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#4]
### Modpack Version

1.0.1

### Describe your issue.

Have tried to manually feed a Sal Ammoniac Accumulator with water buckets but it just places a source block on the outside. Also tried with the tank and the same happens.
Also doesn't seem to accept it if I used pipes to try and feed water in.
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/a7370162-9649-4849-a41b-218849179ccf)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by peisach** [comment]
I have not gotten far enough to test this myself, but I see that theurgy was updated today. Is the bug still present if you substitute the latest version in place of the old?

https://www.curseforge.com/minecraft/mc-mods/theurgy/files/all?page=1&pageSize=20&version=1.21&gameVersionTypeId=6

**Comment by SupaJordy** [comment]
> I have not gotten far enough to test this myself, but I see that theurgy was updated today. Is the bug still present if you substitute the latest version in place of the old?
> 
> https://www.curseforge.com/minecraft/mc-mods/theurgy/files/all?page=1&pageSize=20&version=1.21&gameVersionTypeId=6

Sadly, still the same with the 1.22.3 version of Theurgy.

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/10e86bff-3b87-417f-b1d5-87be20828412)

**Comment by NielsPilgaard** [comment]
Thanks for the report, I've reported it here: https://github.com/klikli-dev/theurgy/issues/187

**Comment by klikli-dev** [comment]
Thanks for testing and finding this! I suspect this has to do with the recipe changes in 1.21 (because the accumulator only accepts fluids it has a recipe for). Will test!
Can you let me know if the tank works for you? (Does it accept sal ammoniac fluid e.g. from buckets)

**Comment by SupaJordy** [comment]
Yes it would appear that I can use a sal ammoniac fluid bucket on the tank and it inserts without issue.

**Comment by klikli-dev** [comment]
> Yes it would appear that I can use a sal ammoniac fluid bucket on the tank and it inserts without issue.

Thanks for confirming! 

It's fixed now, the update will be on curse in a few minutes
