### ISSUE TITLE
Occutlism crushed ore have no tags

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#42]
### Modpack Version

1.5.0

### Describe your issue.

When the foliot crusher crushes ores they drop Empty tag c:dusts. EMI/JEI show the recipe results as mekanism crushed ores for some and modern industrialization for some also.
![2024-07-21_05 02 16](https://github.com/user-attachments/assets/5ada740a-ba53-4add-94a3-d9704244d96a)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by NielsPilgaard** [comment]
Thanks for the report

@klikli-dev Got a big for you 😊

**Comment by MuteTiefling** [comment]
Can confirm this one too. My fission reactor ran out of fuel and I found my uranium crushing Marids sitting around in a pile of barriers :D

**Comment by MuteTiefling** [comment]
Was working fine in `occultism-1.21-neoforge-1.136.4` as near as I can tell. Pack is now on `occultism-1.21-neoforge-1.136.5`

**Comment by calog3no** [comment]
So it seems any thing that the occultism crusher crushes turns into an empty tag result
![2024-07-16_08 14 06](https://github.com/user-attachments/assets/4676c617-80f5-42d9-b630-4c40c48b580d)
. Tested obsidian and demon fruit.

**Comment by flece** [comment]
diamond Ore is working fine :)

**Comment by MuteTiefling** [comment]
There's something else going on here, I think. I've downgraded occultism all the way to 1.134.6 and it has not started working. It was working fine for me in dev though at some point as  I set up a whole mekanism fission reactor based on their crushing... gonna keep digging

**Comment by MuteTiefling** [comment]
ok, yeah it works fine as soon as I remove our recipe additions. swapping them over to a tag output appears to fix the issue

**Comment by MuteTiefling** [comment]
hrm, spoke too soon... issue is back after a restart.

**Comment by MuteTiefling** [comment]
Yeah, just doing a `/reload` fixes it. So there's something goofy with tags again >.< I've removed all of our tag scripts from Kube and still have the issue on first launch until I `/reload`

**Comment by MuteTiefling** [comment]
They also work fine on first launch with KubeJS disabled >.< so it's not a script thing, but likely something with KubeJS itself

**Comment by MuteTiefling** [comment]
OK. Seems to be the tag based stonecutting script I implemented to add chiseled/chipped recipes to the stonecutter. Removing that has fixed this.

**Comment by calog3no** [comment]
just updated my develop repo and crushing seems to be fixed!!!

**Comment by MuteTiefling** [comment]
Don't celebrate just yet :D It broke on me again. 

It does seem to be some interplay between occultism and kubejs, specifically something with one or more of our scripts since it doesn't happen without the scripts... I've narrowed things down some more but it's still not quite clear yet.

**Comment by MuteTiefling** [comment]
I think I've narrowed it down to this script. 

https://github.com/EnigmaticaModpacks/Enigmatica10/blob/master/kubejs/server_scripts/recipes/enigmatica/replace_input.js

Not sure how or why, but any of those replaceInputs breaks the crusher

**Comment by MuteTiefling** [comment]
Alright, thanks for looking into it @klikli-dev. Worst case, I seem to be able to fix it with Kube by replacing the output with our own preferred item. If adding the schema doesn't fix it, then I can just move ahead with this.

**Comment by MuteTiefling** [comment]
Klikli has updated https://www.curseforge.com/minecraft/mc-mods/occultism-kubejs and I can confirm that this does in fact fix the issue :D So I'll go ahead and revert my workaround and we can proceed with this next update. <3 @klikli-dev
