### ISSUE TITLE
missing item tags in extreme reactor and theurgy ores

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#46]
### Modpack Version

1.4.0

### Describe your issue.

both mod's add block tags but not item tags

mekanism sorter requires item tags to sort by

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

DoomSquinter

**Comment by MuteTiefling** [comment]
Thanks for the report! I've relayed them below:

https://github.com/klikli-dev/theurgy/issues/203
https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/157
