### ISSUE TITLE
Cobblestone can't be piped into Mercury Distiller

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#5]
### Modpack Version

1.1.0

### Describe your issue.

The Mercury Distiller from Theurgy won't accept cobblestone unless you can give it 10 at once. I've tried by hand (with 1), through a hopper and a tier 1 Mekanism pipe. Other items that convert on a 1:1 ratio (like iron ingots) can be inserted without issue this way.

To get the Mercury Distiller to accept cobblestone, you need to be holding >10 in your hand or using a pipe that can transfer >10 like the Ultimate Item Transport Pipe from Mekanism.

### Have you modified the modpack?

Yes

### User Modifications

I am using the Theurgy release 1.22.4 that came out today as it fixes the previous issue with the Sal Ammoniac Accumulator issue.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by klikli-dev** [comment]
@NielsPilgaard any way is fine ;) 

In fact for this error I think I know what the problem is, I am using neoforge sized ingredients now which enforce the size on all checks.. going to need to dig into that :D

**Comment by SupaJordy** [comment]
So I'm on 1.2.0 but still have the same issue. Is it fixed in another release?

**Comment by klikli-dev** [comment]
> So I'm on 1.2.0 but still have the same issue. Is it fixed in another release?

@SupaJordy it seems something went wrong on my end as I can still reproduce the bug. Testing this now to provide a fix

**Comment by SupaJordy** [comment]
I seem to have two files:
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/8d04f2b2-4f82-44d5-8373-7d25e5b7be04)

This may be because I downloaded 1.22.4 separately and before I updated the pack. I will remove and try again.

**Comment by SupaJordy** [comment]
Hmmm, no. After removing 1.22.4 and relaunching with just 1.22.5, I still can't manually place 1 cobble into the mercury distiller or use a basic logistical transporter to pipe from a barrel with a stack of cobblestone in it.

![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/d2fe7ffa-7caa-4ce9-84ca-01720093caef)
