### ISSUE TITLE
Tectonic

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica10#51]
### URL

https://www.curseforge.com/minecraft/mc-mods/tectonic

### Why would you like the mod added?

Looks like it plays nice with terralith and would add some lovely rivers/mountains/hills.

Gonna check it out here and report how it feels, but it seems very promising.

**Comment by NielsPilgaard** [comment]
Looking forward to your assessment :D

**Comment by MuteTiefling** [comment]
I'm sold. There have been surprisingly few oddities, like structures in odd positions. Overall it's very seamless. 

It's gonna mess up existing worlds, but better to get that out of the way early on, I suppose. 

I did try reducing the terrain scale from `1.125` to `1.075` and it didn't seem to make much difference. Either in performance or actual size. Maybe best to leave it standard.

![2024-07-23_19 01 17](https://github.com/user-attachments/assets/39c04807-75fe-4389-90c6-c166835d3be3)
![2024-07-23_15 57 01](https://github.com/user-attachments/assets/0be20163-a078-40cb-83e2-849a45ff8edc)
![2024-07-23_15 58 06](https://github.com/user-attachments/assets/23b29d3d-08bd-43ad-a5cf-ae3bfa427e88)
![2024-07-23_19 03 52](https://github.com/user-attachments/assets/155d6c39-bfe9-4213-8608-656e3e8e5451)
![2024-07-23_19 04 12](https://github.com/user-attachments/assets/6e189bb6-1701-426a-83ee-58bf8499dd0e)
![2024-07-23_19 04 51](https://github.com/user-attachments/assets/5bf4403f-2522-4315-b4e6-4b7aa4daef6b)
![2024-07-23_19 05 14](https://github.com/user-attachments/assets/bd48fca9-af46-49e1-abf8-6e768ea3adb4)
![2024-07-23_19 05 51](https://github.com/user-attachments/assets/678e6d9e-2f29-42b6-8530-53460b777794)
![2024-07-23_19 05 53](https://github.com/user-attachments/assets/f5e4f0b8-19e8-4e1a-99fe-96991836ffe5)
![2024-07-23_19 06 15](https://github.com/user-attachments/assets/03e0406c-22a1-4797-a479-e23231e9e1f6)
![2024-07-23_19 06 28](https://github.com/user-attachments/assets/378ef5c0-23c4-49b1-826c-fc3afbff9ab9)
![2024-07-23_19 06 48](https://github.com/user-attachments/assets/9d52214a-d140-479a-819b-15d0af3ae63a)
![2024-07-23_19 07 02](https://github.com/user-attachments/assets/ea215065-212f-41c3-b9b3-4aab09314717)
![2024-07-23_19 07 19](https://github.com/user-attachments/assets/0e28f5ed-b4ff-4b8d-a878-8ff232022f9e)
![2024-07-23_19 07 46](https://github.com/user-attachments/assets/db4aea2b-d2dd-49e0-90f7-1d2da2be9718)
![2024-07-23_19 08 11](https://github.com/user-attachments/assets/e0e8aaec-c749-468e-9b21-5d31d700e91f)
![2024-07-23_19 08 37](https://github.com/user-attachments/assets/f62dc366-19ad-4c42-b4ca-5934c6cb0f86)
![2024-07-23_19 08 56](https://github.com/user-attachments/assets/6910be31-06bf-409a-aea6-4c4fc4306006)
![2024-07-23_19 09 19](https://github.com/user-attachments/assets/d7162f9c-5a57-4a57-bed0-ca496aa439bd)

**Comment by flece** [comment]
thats all nice and so, but i like Luke Warm Ocean next to "Beach" next to Jungle....show some pictures for me pls :)

**Comment by NielsPilgaard** [comment]
Messing up existing worlds - We're only talking chunk borders right?

**Comment by MuteTiefling** [comment]
Correct, just chunk borders
