### ISSUE TITLE
Breaking "Containment Jar" from ars_nouveau gets me an "Connection Lost " 

### ISSUE THREAD

**Issue by flece** [EnigmaticaModpacks/Enigmatica10#55]
### Modpack Version

1.6.0

### Describe your issue.

despite the error message iam playing on SP

ars_nouveau-1.21.0-5.0.1-all.jar
ars_nouveau-1.21.0-5.0.2-all.jar

### Crash Report

https://gist.github.com/flece/78fbc55bfac6423f94b1843a80c4a415

### Latest Log

https://gist.github.com/flece/899eca574f139ac63de967bf28c714f0

### Have you modified the modpack?

Yes

### User Modifications

manually updated Ars to next and second next version

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, and for adding to the open issue on Ars's issue tracker 👍
