### ISSUE TITLE
Crusher recipes removed

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#56]
### Modpack Version

1.7.0 develop branch

### Describe your issue.

All are ore dusts no longer listed under Ocultism crusher recipes. I know it's a WIP just wanted to make you aware.
![2024-07-27_08 34 38](https://github.com/user-attachments/assets/73601c42-03ec-4a0d-a239-8d1280cba7de)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by MuteTiefling** [comment]
Hrm, yeah seems to have happened with the last few kubejs and occultism versions. @klikli-dev

**Comment by MuteTiefling** [comment]
What's odd is that the previous workaround script also doesn't work to fix it now. When it loops through all the crusher recipes, it doesn't find any of the missing recipes, wheras it did before and could re-implement them.

Removing KubeJS fixes it, as expected. I tried downgrading KubeJS but was just getting bad datapack errors upon trying to load any world.

**Comment by calog3no** [comment]
I wonder if that workaround script was fixing the crushed ores having no tags, but this feels like the initial crusher recipe issue from an earlier version of the pack that eliminated the ore crushing recipes all together.

**Comment by MuteTiefling** [comment]
It was looping on all the recipes to replace the tag output with an item output. Now it doesn't see any of the ore recipes, but the other tagged recipes (obsidian dust, for example) are being found without issue.

It's like the condition on these recipes is being broken by kubejs

**Comment by klikli-dev** [comment]
@MuteTiefling is it possible to reproduce this with e.g. just occultism, kubejs and one other ore mod?
Then I can debug it and maybe talk to the Kube people directly.

**Comment by Kanzaji** [comment]
So, it appears that one of our Scripts is causing this.
Currently running EE-Dev with latest Neo (143-Stable), Latest KubeJS (117) and Latest Occultism (1.140.0), and the issue only appears when I loaded the scripts from E10 (Even tho I've got 28 errors because of missing mods), the crushing recipes work just fine with just the default kubejs recipes.

**Comment by MuteTiefling** [comment]
@klikli-dev I setup up a small instance with the mods in the attached crash report.
[crash-2024-07-29_08.31.10-client.txt](https://github.com/user-attachments/files/16412972/crash-2024-07-29_08.31.10-client.txt)

With just those mods and no KubeJS scripts, your stuff works fine.

As soon as I add a small script to modify unrelated recipes (generic replacement script to replace `minecraft:feathers` with `#c:feathers`) your recipes went away. 

[latest.log](https://github.com/user-attachments/files/16413106/latest.log)

**Comment by MuteTiefling** [comment]
Here's an export of the instance, actually. Maybe that'll help [e10 test update.zip](https://github.com/user-attachments/files/16413118/e10.test.update.zip)

**Comment by klikli-dev** [comment]
Thanks, I'll check that out!

**Comment by klikli-dev** [comment]
KubeJS 2100.7.0-build.118 fixes this again - not yet out on curse, but Lat should push it soon.

**Comment by MuteTiefling** [comment]
We're in business :D 
![image](https://github.com/user-attachments/assets/edfdf6de-6e66-4979-a3d4-8d1209a45867)
