### ISSUE TITLE
DiscCord

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica10#59]
### URL

https://www.curseforge.com/minecraft/mc-mods/disccord

### Why would you like the mod added?

Lets the player make custom music discs to play in their world. Does require some setup and external programs (FFmpeg and YoutubeDL) but seems pretty cool

**Comment by Mrbysco** [comment]
Client and server. The mod adds a new item and sound event so both sides need the mod. 
The music is only downloaded client-side.

**Comment by MommyHeather** [comment]
I meant the requirement for ffmpeg + yt-dlp, the mod itself would naturally have to be present on both. Good to know those tools are required on the client though.


A big question though - what happens if a user *doesn't* install these?

**Comment by Mrbysco** [comment]
The ffmpeg and youtubedl are only required client-side. They are only used the first time the record is played (for the player), the song will be downloaded locally and streamed ingame.

If the user doesn't install them it will only show a red message in chat stating that ffmpeg / youtubedl are missing and to check the log for instructions how to install

**Comment by Mrbysco** [comment]
This is only the initial stage of the mod, I plan to improve upon the system later. Just wanted the initial version live. 
If I can find libraries that can do the same thing I can potentially remove the need for ffmpeg or youtubedl (depending on which has a decent library that works cross-platform)
