### ISSUE TITLE
Infinite redstone/glowstone/sandstone from stone

### ISSUE THREAD

**Issue by rybacki-t** [EnigmaticaModpacks/Enigmatica10#60]
### Modpack Version

1.6.0

### Describe your issue.

You can use minecraft stonecutter to change stone into "Chisel Reborn" variants of redstone/sandstone/glowstone blocks, and then change them into the default block.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kemotomek

**Comment by MuteTiefling** [comment]
Oops! I see what I did there. Thanks for the report, I'll get that fixed up quick
