### ISSUE TITLE
Minnow from Aquaculture has no food value

### ISSUE THREAD

**Issue by rybacki-t** [EnigmaticaModpacks/Enigmatica10#63]
### Modpack Version

1.6.0

### Describe your issue.

Not sure if bug, or a feature, but Minnow from Aquaculture is the only fish without food value and cannot be made into fillet. It can still be used as generic fish in breeding/Ars Nouveau/Occultism recipes.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kemotomek

**Comment by MuteTiefling** [comment]
A minnow fillet would be a terribly unsatisfying meal :D 

They're tiny fish (smaller than a finger) and are used as bait, both in the mod and in real life.

**Comment by NielsPilgaard** [comment]
> Also, maybe worth mentioning, there is no recipe to browse for Raw Fish Fillet, even though you can craft it using any of the Fillet Knives and most of the fish from Aquaculture (as of now I only know about the Minnow not being usable in the recipe).

This will be fixed in the next update 👍 
https://github.com/TeamMetallurgy/Aquaculture/issues/459
