### ISSUE TITLE
Occultism dimensional storage does not sync search bar with EMI

### ISSUE THREAD

**Issue by calog3no** [EnigmaticaModpacks/Enigmatica10#64]
### Modpack Version

develop branch 

### Describe your issue.

The search bar for occutislm dimensional storage will not allow you to type if the sync with JEI is enabled. It works as intended when not synced, and sort function is not affected.

### Have you modified the modpack?

Yes

### User Modifications

Updated Ars Nouveau to ver  1.21.0-5.0.5-all.jar

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

calog3no

**Comment by klikli-dev** [comment]
release/v1.21-1.143.0 will add this feature :)

I completely forgot that EMI would need a separate integration

**Comment by NielsPilgaard** [comment]
Lovely, thank you!
