### ISSUE TITLE
Carry On

### ISSUE THREAD

**Issue by CadavezUSP** [EnigmaticaModpacks/Enigmatica10#66]
### URL

https://www.curseforge.com/minecraft/mc-mods/carry-on

### Why would you like the mod added?

Is a good option to move things (chests mainly) without breaking or lose some config

**Comment by MuteTiefling** [comment]
Cardboard boxes work well too and tend to cause fewer issues.

**Comment by NielsPilgaard** [comment]
I'd rather not add Carry On, it was a ton of work to have it in Enigmatica 2.
