### ISSUE TITLE
crash while rendering a occultism crusher foliot

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#67]
### Modpack Version

1.7.0

### Describe your issue.

since updating to 1.7.0 I've had about 3 crashes, all with occultism

this latest crash happened when I sat down and unpaused game and backup kicked off and I turned and looked at the crusher foliot and it hard crashed to desktop

I can't reload this save anymore

### Crash Report

https://gist.github.com/DoomSquirter/93993d14098d7196395871e33de8a34d

### Latest Log

https://gist.github.com/DoomSquirter/576e03719aeaf0e87e87f32aff8f5065

### Have you modified the modpack?

Yes

### User Modifications

I readded the crafting table on a stick mod that was removed but this was something I did 2 updates ago

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

DoomSquinter

**Comment by NielsPilgaard** [comment]
@klikli-dev help please 😅

**Comment by klikli-dev** [comment]
I fear I have to talk to the smart people at Geckolib to see how to fix that @NielsPilgaard

**Comment by NielsPilgaard** [comment]
Roger, thank you 👍 do you know of a workaround?

**Comment by klikli-dev** [comment]
Sadly no - I am not sure how MC rendering works but potentially putting the spirit in a box where it is not seen (and maybe not rendered, if MC does frustum calling) may help :D

**Comment by DoomSquirter** [comment]
figured I'd see if 1.8.0 fixed the login to world crash and it does
but I think the problem might be related to the dire sword with the mob finder.  I rclicked the foliot crusher that is causing the mess with my sword instinctively and the world dies again.  
now the world is again crash on load so I guess it was setting the glowing effect on the foliot altho I noticed that the geckolib update supposedly fixed exactly that.
so I deleted the save and copied over the one before I tried to load the pack and it loads then immediately disabled the mob finder on the sword.
Still not sure how it fixed my corrupt save on load that I had from playing 1.7.0 but I think I can absolutely say it's the glowing effect that was causing all these issues.

**Comment by DoomSquirter** [comment]
I just want to confirm the whole "fixed in next release" label. 

We are not talking about 1.8.0 right?  cause as of 1.8.0 the problem still persists.

Only asking clarification since 1.8.0 just got an announcement in the discord

**Comment by NielsPilgaard** [comment]
> I just want to confirm the whole "fixed in next release" label.
> 
> We are not talking about 1.8.0 right? cause as of 1.8.0 the problem still persists.
> 
> Only asking clarification since 1.8.0 just got an announcement in the discord

`fixed in next release` when the issue is closed means it's fixed in a released version, when the issue is open it means the fix has not yet been released.

But re-reading the issue, this doesn't sound fixed 😅

**Comment by DoomSquirter** [comment]
so, before I updated to latest latest, I tried replicating this in a test world and couldn't. 

Let's just assume that this was fixed upstream already and I'm closing this.
