### ISSUE TITLE
Crash when uses for quartz

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica10#7]
### Modpack Version

in-dev

### Describe your issue.

Comes up when viewing uses for quartz. Seems to be the crusher render for occultism. 

### Crash Report

https://gist.github.com/MuteTiefling/ac6d6e4bd95c42b7a8adbc35b3146108

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
@klikli-dev Got another for you :D

**Comment by klikli-dev** [comment]
Fix already building :)
