### ISSUE TITLE
Fruit Basket not registered in kitchen (Cooking for Blockheads)

### ISSUE THREAD

**Issue by rybacki-t** [EnigmaticaModpacks/Enigmatica10#70]
### Modpack Version

1.7.0

### Describe your issue.

Fruit Basket contents are not available while the Basket is put on a Counter. It will work when placed on the floor, fridge, spice rack and tool rack.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kemotomek

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
