### ISSUE TITLE
Using upgrades on Pollen Sifter crashes the game

### ISSUE THREAD

**Issue by rybacki-t** [EnigmaticaModpacks/Enigmatica10#71]
### Modpack Version

1.8.0

### Describe your issue.

Using the Upgrade: Speed from ProductiveLib on Pollen Sifter crashes the game - both shift + right click and input in GUI. I have tried Upgrade: Productivity Alpha as well with the same result. Attached the last two crash reports.

### Crash Report

https://gist.github.com/rybacki-t/6c668424a62080419c96c3a2ce2852e0

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kemotomek

**Comment by NielsPilgaard** [comment]
Thanks for the report, I've relayed it 👍
