### ISSUE TITLE
Chococraft: Ghysal plants not usable in vanilla Composter

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#72]
### Modpack Version

1.8.0

### Describe your issue.

In EMI all the Ghysal type plants from Chococraft show that they are usable in the composter and provide quite a lot of bonemeal. However, in game they are actually not usable with the composter at all. 

I tested this with Loverly Ghysal, Ghysal Greens and their seeds and even Golden Ghysal. Non are able to be used in the composter.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by MuteTiefling** [comment]
Thanks for the report, I've relayed the issue!
