### ISSUE TITLE
Chococraft: Choco pens not healing Chocobos

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#73]
### Modpack Version

1.8.0

### Describe your issue.

I have a 7x7x5 walled chocobo pen with several injured chocobos in it. The pen is supposed to heal injured chocobos over time but after multiple in-game days they are still at the same health.

the pen is 7x7x5 with a Chococraft straw floor and a filled cauldron on one side. I tried moving the cauldron to the center but it made no difference.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by MuteTiefling** [comment]
Seems there's no issue.

Pen has to be made of Straw. Chocobo must be tamed. 
![image](https://github.com/user-attachments/assets/470e389c-e5eb-43a2-9387-9b06d1b38669)

I hit this guy with a splash harm potion and when I checked it an hour later, it was healed up.

**Comment by MuteTiefling** [comment]
@Drytchnath can you see if you're still able to replicate your issue with the above information?
