### ISSUE TITLE
Genetics: Resequenced: Matching Genes in Plasmid Infuser not giving correct amount of DNA points

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#74]
### Modpack Version

1.8.0

### Describe your issue.

When using matching DNA Helixes to create Plasmids the UI will say it gives +2 DNA points towards completion but they actually only give 1 point. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by MuteTiefling** [comment]
Thanks for the report, I've relayed the issue!
