### ISSUE TITLE
Just Dire Things: Slight buff for Weapons and Tools

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#75]
### Describe your suggestion

Just Dire Things has some fairly nice gear but I feel it is overshadowed by Mekanism's Osmium tools and armor which is available much earlier and is much lower effort to craft.

For example, a Blazegold sword only does 7 damage and requires a trip to the nether but only deals 7 base Damage and requires a fair amount of gold. An Osmium sword can be had within less than an hour, deals 8 damage and has over 1k durability.

My suggestion is just a minor buff to Just Dire Things to make it more rewarding to require the tools and armor

### Why would you like this added/changed?

Make Just Dire Things a more attractive option for early and mid-game gear

**Comment by MuteTiefling** [comment]
JDT tools have the advantage of being upgraded, with some of the upgrades being very powerful.

I'm also not sure to what degree we can actually buff them, but I'll look into it. When a similar request was made in E6, however, our only real option was to nerf osmium.

I'm not sure I want to go that route here though as they really just make the early game more bearable.

**Comment by rybacki-t** [comment]
I agree with the upgrades being powerful - I am currently using a Celestigem armor/tools and they were not that hard to get (along with crafting the upgrades). My only suggestion to improve them, would be giving them a bit more power capacity, especially chest plate, boots and bow. Elytra upgrade gives just a few seconds of flight and the boots run of energy barely outside my base region.

I may have not found an easy way to carry some extra energy to recharge on the go though. but no spoilers please 😛 Just disregard if I am missing something ^^

**Comment by MuteTiefling** [comment]
Yeah the mod is balanced around you needing to carry energy with you. It includes options for doing so, however. There are other outings too in Powah.

**Comment by DoomSquirter** [comment]
my 2 cents, I noticed this as well
I just took it as par for the course as counterbalance to the utility of the tools

**Comment by Drytchnath** [comment]
Looking at the celestigem and up, yea those are strong, but the first two tiers don't really feel worth it.

**Comment by MuteTiefling** [comment]
Looked into this a bit and I'm having trouble with it. Seems like kubejs should be able to modify durability at least in a startup script but it's not working for me.

May not be worth the effort. Especially now that we've got evilcraft and a way to repair items indefinitely.

**Comment by MuteTiefling** [comment]
Between evilcraft and backpacks for repair, and considering the constant buffs to JDT, I think this is ultimately fine as is. Gonna close this up.
