### ISSUE TITLE
Multiverse Traveler entity crashing game (probably)

### ISSUE THREAD

**Issue by rybacki-t** [EnigmaticaModpacks/Enigmatica10#76]
### Modpack Version

1.6.0

### Describe your issue.

I went to the End-like dimension and spawned underground. The Traveler's health bar appeared, so I located it on the map and went up. As soon as I dug to the surface and looked around, my game crashed (and kept crashing when I tried to load the world, as I was already on the surface).

Spawning the Collector with Universal Treasure caused no issues (both in overworld, and the dimension where he fled).

I have seen a similar issue with Foliot Crusher from Occultism (hehe, foliot crasher), but I don't know if it has the same cause.

### Crash Report

https://gist.github.com/rybacki-t/422989a1f41022f8b8e03ffc775b224f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kemotomek

**Comment by NielsPilgaard** [comment]
Thanks for the report, please update to 1.8.0 and see if the issue persists :)

**Comment by rybacki-t** [comment]
Updated - spent ages flying around, but finally got one and did not crash!

**Comment by NielsPilgaard** [comment]
Glad to hear that :D

**Comment by zazum03** [comment]
Having this same issue on version 1.9.0.

Loaded into an End biome Multiverse, walked around for a little, and saw the Traveler healthbar pop up. As soon as he loaded in, my game crashed to desktop and I am now unable to load into that world.

https://gist.github.com/zazum03/9f2005bc43aad62fc71f220b5a9c01d1

**Comment by MuteTiefling** [comment]
We might be better off just removing this one next update. 

Seems like there's a new person every other day in discord running into it and there doesn't appear to be any recent activity on their github.

**Comment by NielsPilgaard** [comment]
Alright 👍

**Comment by MuteTiefling** [comment]
'Fixed' as multiverse is no longer in the pack
