### ISSUE TITLE
"Loot not generated yet" incorrectly showing in Jade

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica10#77]
### Modpack Version

1.8.0

### Describe your issue.

Lootr containers, when looked at, will show "Loot not generated yet" in Jade:
![image](https://github.com/user-attachments/assets/bb956b1a-f0bc-4496-802b-444d809dbbff)
Even though the loot is definitely already generated, even taken out of the chest by a player.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

SeoY

**Comment by NielsPilgaard** [comment]
Thanks for the report, the issue was fixed here: https://github.com/Snownee/Jade/issues/448
