### ISSUE TITLE
add all ores to occultism miners

### ISSUE THREAD

**Issue by DoomSquirter** [EnigmaticaModpacks/Enigmatica10#78]
### Describe your suggestion

on 1.8
just made a master miner marid
it is not picking up evilcraft ores
it is not picking up uranite from powah
it's getting MI ores fine
also getting mekanism ores fine
don't see the theurgy ones either
not sure what I'm missing
don't see this as a bug, but a pack augmentation

### Why would you like this added/changed?

it takes a bit to make the master miner.  would be nice if it had all the ores as candidates

**Comment by MuteTiefling** [comment]
@klikli-dev might actually want to just add these by default. They already support a bunch of other things

**Comment by klikli-dev** [comment]
I agree, that should be builtin so all packs profit from it. I will look into that!

**Comment by klikli-dev** [comment]
[v1.21-1.148.0](https://github.com/klikli-dev/occultism/tree/release/v1.21-1.148.0) adds the ores (also adds uraninite and evil ores to theurgy)
