### ISSUE TITLE
Find Me: Not working with non-vanilla storage/blocks

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#82]
### Modpack Version

1.8.0

### Describe your issue.

The Find Me mod is not working with non-vanilla inventories like Iron Chest. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by NielsPilgaard** [comment]
Thanks for the report!

@Buuz135 double ping for good measure :D

**Comment by MuteTiefling** [comment]
Very possible this is only iron chests being problematic. Early on, ae2 also couldn't read them and I was having issues recently with an RLC being unable to get a comparator signal from them.

Could you test on other chests to see? There should be a few from macaws

**Comment by Drytchnath** [comment]
Just tested with an oak diamond barrel from Soph Storage and a Macaw Wardrobe and still wasn't working in 1.9.

Just to check, I tried a vanilla chest again and in 1.9 it wasn't working in those either anymore

**Comment by NielsPilgaard** [comment]
All of the above containers are working in development 👍

**Comment by Buuz135** [comment]
Are you sure you are pressing the right keybind and there isnt a keybind conflict?

**Comment by Drytchnath** [comment]
> Are you sure you are pressing the right keybind and there isnt a keybind conflict?

I actually went and unbound everything else from Y except Find Me but it still wasn't working. I'm not really sure why it works in dev and not in my game. Maybe it will work in next release.
