### ISSUE TITLE
Just Dire Things: Tree Feller affecting accelerated leaf decay

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#84]
### Modpack Version

1.8.0

### Describe your issue.

When using the Tree Feller upgrade on a JDT Blazegold axe, leaves do not decay fast and instead follow vanilla leaf decay.

In case it matters the axe had the Silk Touch and Efficiency 4 enchants.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by NielsPilgaard** [comment]
Thanks for the report, I've relayed the issue.
