### ISSUE TITLE
Occultism: Unable to auto-pull materials to craft from Dimensional Storage

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#85]
### Modpack Version

1.9

### Describe your issue.

When accessing Dimensional Storage via the remote or actual pedestal it is unable to pull items to craft via EMI. It says there is not enough despite having thousands of the required materials (ex: not being able to craft an iron block despite having thousands of iron ingots).

Pulling the items out of storage and into my player inventory directly allows it to function and autofill the crafting grid via EMI.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by NielsPilgaard** [comment]
Thanks for the report. 
I was unable to use the latest Occultism and JEI when updating the pack, due to latest JEI only supporting 1.21.1. 
Fixing this might have to wait till we update to Minecraft 1.21.1, so we can grab the most recent mod versions.

You can also downgrade to 1.8.0 of course 😊

**Comment by calog3no** [comment]
I updated to the most recent ver of Occultism and Modonomicon and I am able pull items from dimensional storage when crafting within the storage interface from Occultism.
