### ISSUE TITLE
unable to craft the exalted crafter from evilcraft mod

### ISSUE THREAD

**Issue by mazencj** [EnigmaticaModpacks/Enigmatica10#86]
### Modpack Version

1.8.0

### Describe your issue.

So, I wanted to craft the exalted crafter but the crushed dark gem doesn't have a recipe or a drop from the ore.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

mazencj#7248

**Comment by mazencj** [comment]
Someone commented about how to get it, and I didn't bother to read the guide book from the mod itself.

**Comment by NielsPilgaard** [comment]
So... all good? :)

**Comment by mazencj** [comment]
> So... all good? :)

yeah, So it was a fortune in a pickaxe what needed to get the crushed dark gem
