### ISSUE TITLE
EvilCraft: using Purifier with Blook on Enchanted Book crashes the game

### ISSUE THREAD

**Issue by rybacki-t** [EnigmaticaModpacks/Enigmatica10#88]
### Modpack Version

1.9.0

### Describe your issue.

Using the Purifier from EvilCraft with Blook on Enchanted Book crashes the game - I was hoping to split the enchantments from random enchanted book I found. Using the Purifier with Blook on items works without issues.

### Crash Report

https://gist.github.com/rybacki-t/6d0e0d3cb2f6e5c125c0eba37151be07

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kemotomek

**Comment by NielsPilgaard** [comment]
Thanks for the report 👍 I've relayed it to the appropriate mod's issue tracker.
