### ISSUE TITLE
Ars Nouveau: Volcanic Sourcelink unable to accept any fuel

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#89]
### Modpack Version

1.9

### Describe your issue.

The Ars Volcanic Sourcelink is no longer able to accept fuel items in order to produce source. Tested with JDT Blaze Ember, Coal/Coal Blocks, Oak Logs and Blazing Archwood Logs. Pedestal is 1 block away from sourcelink as is jar and was producing source without issues in 1.8.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by MuteTiefling** [comment]
Thanks for the report! I've relayed to their discord.

Out of curiosity, does it help to break and replace the source link?

**Comment by Drytchnath** [comment]
Just checked, broke and replaced sourcelink, pedestal and mana jar, no difference

**Comment by MuteTiefling** [comment]
Alright. I'm fairly certain that's intended to only work when adjacent.
