### ISSUE TITLE
Nullscape

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica10#91]
### URL

https://www.curseforge.com/minecraft/mc-mods/nullscape

### Why would you like the mod added?

Same devs as Terralith, and it brings some nice variance to The End.

**Comment by NielsPilgaard** [comment]
We'll add this once it's marked as 1.21.1 compatible 👍

**Comment by SeooY** [comment]
Revisiting this, Nullscape has now a 1.21.1 compatible release
https://www.curseforge.com/minecraft/mc-mods/nullscape/files/5759158
