### ISSUE TITLE
Not Enough Glyphs

### ISSUE THREAD

**Issue by SeooY** [EnigmaticaModpacks/Enigmatica10#92]
### URL

https://www.curseforge.com/minecraft/mc-mods/not-enough-glyphs

### Why would you like the mod added?

Nice addon for Ars Nouveau. It has some repackaged glyphs originally from Too Many Glyphs. Same dev as Ars Elemental.

**Comment by MommyHeather** [comment]
Too Many Glyphs, then Not Enough Glyphs... what's next, Just Enough Glyphs?
